### ISSUE TITLE
AutoPaging with Mapping Doesnt Work

### ISSUE THREAD

**Issue by ilushka85** [datastax/csharp-driver#87]
How would you get auto paging while using a mapper work?  It seems that autopagging is set to false by default and no way to turn it before running a fetch thru the mapper.

**Comment by avalanche123** [comment]
Please use the mailing list or jira for these questions

**Comment by ilushka85** [comment]
Well this is actually an issue as in 2.5.1 this behavior no longer works as it should.  Pre 2.5.1 it works.

**Comment by avalanche123** [comment]
@ilushka85 could you please [open an issue in csharp-driver jira issue tracker](https://datastax-oss.atlassian.net/browse/CSHARP) or [ask a question on the mailing list](https://groups.google.com/a/lists.datastax.com/forum/#!forum/csharp-driver-user)

**Comment by ilushka85** [comment]
I submitted a pull request that fixes this issue introduced in 2.5.1

**Comment by avalanche123** [comment]
thanks @ilushka85, you rock!

**Comment by ilushka85** [comment]
@avalanche123 how soon do you think you can get this one pushed to nuget as its a very minior fix?

**Comment by avalanche123** [comment]
@ilushka85 this is really up to @jorgebay, watch out for his response on your pull request
